In [1]:
import pandas as pd 
import numpy as np

In [2]:
pd.set_option('display.max_columns',None)

In [3]:
loan_df = pd.read_csv(r'D:\Work\Personal project\Credit scoring\Credit-Scoring\Input files\loan.csv')

C:\Users\hexs2\AppData\Local\Temp\ipykernel_26264\659681136.py:1: DtypeWarning: Columns (0: desc, 1: next_pymnt_d, 2: verification_status_joint, 3: sec_app_earliest_cr_line, 4: hardship_type, 5: hardship_reason, 6: hardship_status, 7: hardship_start_date, 8: hardship_end_date, 9: payment_plan_start_date, 10: hardship_loan_status, 11: debt_settlement_flag_date, 12: settlement_status, 13: settlement_date) have mixed types. Specify dtype option on import or set low_memory=False.
  loan_df = pd.read_csv(r'D:\Work\Personal project\Credit scoring\Credit-Scoring\Input files\loan.csv')

In [4]:
loan_df.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,2500,2500,2500.0,36 months,13.56,84.92,C,C1,Chef,10+ years,RENT,55000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,109xx,NY,18.24,0.0,Apr-2001,1.0,NaN,45.0,9.0,1.0,4341,10.3,34.0,w,2386.02,2386.02,167.02,167.02,113.98,53.04,0.0,0.0,0.0,Feb-2019,84.92,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,16901.0,2.0,2.0,1.0,2.0,2.0,12560.0,69.0,2.0,7.0,2137.0,28.0,42000.0,1.0,11.0,2.0,9.0,1878.0,34360.0,5.9,0.0,0.0,140.0,212.0,1.0,1.0,0.0,1.0,NaN,2.0,NaN,0.0,2.0,5.0,3.0,3.0,16.0,7.0,18.0,5.0,9.0,0.0,0.0,0.0,3.0,100.0,0.0,1.0,0.0,60124.0,16901.0,36500.0,18124.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,30000,30000,30000.0,60 months,18.94,777.23,D,D2,Postmaster,10+ years,MORTGAGE,90000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,713xx,LA,26.52,0.0,Jun-1987,0.0,71.0,75.0,13.0,1.0,12315,24.2,44.0,w,29387.75,29387.75,1507.11,1507.11,612.25,894.86,0.0,0.0,0.0,Feb-2019,777.23,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,1208.0,321915.0,4.0,4.0,2.0,3.0,3.0,87153.0,88.0,4.0,5.0,998.0,57.0,50800.0,2.0,15.0,2.0,10.0,24763.0,13761.0,8.3,0.0,0.0,163.0,378.0,4.0,3.0,3.0,4.0,NaN,4.0,NaN,0.0,2.0,4.0,4.0,9.0,27.0,8.0,14.0,4.0,13.0,0.0,0.0,0.0,6.0,95.0,0.0,1.0,0.0,372872.0,99468.0,15000.0,94072.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,5000,5000,5000.0,36 months,17.97,180.69,D,D1,Administrative,6 years,MORTGAGE,59280.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,490xx,MI,10.51,0.0,Apr-2011,0.0,NaN,NaN,8.0,0.0,4599,19.1,13.0,w,4787.21,4787.21,353.89,353.89,212.79,141.10,0.0,0.0,0.0,Feb-2019,180.69,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,110299.0,0.0,1.0,0.0,2.0,14.0,7150.0,72.0,0.0,2.0,0.0,35.0,24100.0,1.0,5.0,0.0,4.0,18383.0,13800.0,0.0,0.0,0.0,87.0,92.0,15.0,14.0,2.0,77.0,NaN,14.0,NaN,0.0,0.0,3.0,3.0,3.0,4.0,6.0,7.0,3.0,8.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,136927.0,11749.0,13800.0,10000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,4000,4000,4000.0,36 months,18.94,146.51,D,D2,IT Supervisor,10+ years,MORTGAGE,92000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,985xx,WA,16.74,0.0,Feb-2006,0.0,NaN,NaN,10.0,0.0,5468,78.1,13.0,w,3831.93,3831.93,286.71,286.71,168.07,118.64,0.0,0.0,0.0,Feb-2019,146.51,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,686.0,305049.0,1.0,5.0,3.0,5.0,5.0,30683.0,68.0,0.0,0.0,3761.0,70.0,7000.0,2.0,4.0,3.0,5.0,30505.0,1239.0,75.2,0.0,0.0,62.0,154.0,64.0,5.0,3.0,64.0,NaN,5.0,NaN,0.0,1.0,2.0,1.0,2.0,7.0,2.0,3.0,2.0,10.0,0.0,0.0,0.0,3.0,100.0,100.0,0.0,0.0,385183.0,36151.0,5000.0,44984.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,30000,30000,30000.0,60 months,16.14,731.78,C,C4,Mechanic,10+ years,MORTGAGE,57250.0,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,212xx,MD,26.35,0.0,Dec-2000,0.0,NaN,NaN,12.0,0.0,829,3.6,26.0,w,29339.02,29339.02,1423.21,1423.21,660.98,762.23,0.0,0.0,0.0,Feb-2019,731.78,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,116007.0,3.0,5.0,3.0,5.0,4.0,28845.0,89.0,2.0,4.0,516.0,54.0,23100.0,1.0,0.0,0.0,9.0,9667.0,8471.0,8.9,0.0,0.0,53.0,216.0,2.0,2.0,2.0,2.0,NaN,13.0,NaN,0.0,2.0,2.0,3.0,8.0,9.0,6.0,15.0,2.0,12.0,0.0,0.0,0.0,5.0,92.3,0.0,0.0,0.0,157548.0,29674.0,9300.0,32332.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

### Master Feature Reference Table

In [5]:
# Auto-generate profile
profile = pd.DataFrame({
    'column': loan_df.columns,
    'dtype': loan_df.dtypes.values,
    'pct_missing': (loan_df.isnull().sum() / len(loan_df) * 100).round(2).values,
    'n_unique': loan_df.nunique().values,
    'sample_value': [loan_df[col].dropna().iloc[0] if loan_df[col].notna().any() else None for col in loan_df.columns]
})

# Merge with data dictionary (assuming you load it as a loan_df with 'column' and 'description')
data_dict = pd.read_excel(r'D:\Work\Personal project\Credit scoring\Credit-Scoring\Input files\LCDataDictionary.xlsx')  # adjust to actual file
profile = profile.merge(data_dict, left_on='column', right_on='LoanStatNew', how='left')

sample_loan = loan_df.sample(n=300,random_state=42)

profile.head()
# profile.to_csv('feature_reference_table.csv', index=False)
# sample_loan.to_csv('300_sample_loan.csv',index=False)

,column,dtype,pct_missing,n_unique,sample_value,LoanStatNew,Description
0,id,float64,100.0,0,None,id,A unique LC assigned ID for the loan listing.
1,member_id,float64,100.0,0,None,member_id,A unique LC assigned Id for the borrower member.
2,loan_amnt,int64,0.0,1572,2500,loan_amnt,The listed amount of the loan applied for by t...
3,funded_amnt,int64,0.0,1572,2500,funded_amnt,The total amount committed to that loan at tha...
4,funded_amnt_inv,float64,0.0,10057,2500.0,funded_amnt_inv,The total amount committed by investors for th...

In [6]:
profile[profile['pct_missing']!=0]

,column,dtype,pct_missing,n_unique,sample_value,LoanStatNew,Description
0,id,float64,100.00,0,None,id,A unique LC assigned ID for the loan listing.
1,member_id,float64,100.00,0,None,member_id,A unique LC assigned Id for the borrower member.
10,emp_title,str,7.39,512694,Chef,emp_title,The job title supplied by the Borrower when ap...
11,emp_length,str,6.50,11,10+ years,emp_length,Employment length in years. Possible values ar...
18,url,float64,100.00,0,None,url,URL for the LC page with listing data.
...,...,...,...,...,...,...,...
140,settlement_status,str,98.54,3,ACTIVE,settlement_status,The status of the borrower’s settlement plan. ...
141,settlement_date,str,98.54,89,Feb-2019,settlement_date,The date that the borrower agrees to the settl...
142,settlement_amount,float64,98.54,21519,5443.0,settlement_amount,The loan amount that the borrower has agreed t...
143,settlement_percentage,float64,98.54,2045,65.0,settlement_percentage,The settlement amount as a percentage of the p...
144,settlement_term,float64,98.54,40,18.0,settlement_term,The number of months that the borrower will be...

## 1. High-level EDA

In [7]:
print('loan_df shape:',loan_df.shape)

loan_df shape: (2260668, 145)

Check target balance

In [8]:
# Check unique value of loan_status to identify which value are needed and decide to combine or not
print(loan_df['loan_status'].unique())

loan_status_unique_value = loan_df.copy()
loan_status_unique_value['record_count'] = loan_status_unique_value['loan_status']
loan_status_unique_value = loan_status_unique_value.groupby(['loan_status'])['record_count'].count().reset_index()

loan_status_unique_value

<StringArray>
[                                            'Current',
                                          'Fully Paid',
                                  'Late (31-120 days)',
                                     'In Grace Period',
                                         'Charged Off',
                                   'Late (16-30 days)',
                                             'Default',
  'Does not meet the credit policy. Status:Fully Paid',
 'Does not meet the credit policy. Status:Charged Off']
Length: 9, dtype: str

                                         loan_status  record_count
0                                        Charged Off        261655
1                                            Current        919695
2                                            Default            31
3  Does not meet the credit policy. Status:Charge...           761
4  Does not meet the credit policy. Status:Fully ...          1988
5                                         Fully Paid       1041952
6                                    In Grace Period          8952
7                                  Late (16-30 days)          3737
8                                 Late (31-120 days)         21897

In [9]:
# From above findings, 'Does not meet the credit policy. Status:Fully Paid' will be rename to 'Fully Paid'
# 'Charged Off', 'Default', 'Does not meet the credit policy. Status:Charged Off' as 'Bad Loan'

loan_df['loan_status_clean'] = loan_df['loan_status'].replace({
    'Default':'Bad Loan',
    'Does not meet the credit policy. Status:Charged Off':'Bad Loan',
    'Charged Off':'Bad Loan',
    'Does not meet the credit policy. Status:Fully Paid':'Fully Paid'
})

loan_status_unique_value2 = loan_df.copy()
loan_status_unique_value2['record_count'] = loan_status_unique_value2['loan_status_clean']
loan_status_unique_value2 = loan_status_unique_value2.groupby(['loan_status_clean'])['record_count'].count().reset_index()
loan_status_unique_value2

C:\Users\hexs2\AppData\Local\Temp\ipykernel_26264\2154765200.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  loan_df['loan_status_clean'] = loan_df['loan_status'].replace({

    loan_status_clean  record_count
0            Bad Loan        262447
1             Current        919695
2          Fully Paid       1043940
3     In Grace Period          8952
4   Late (16-30 days)          3737
5  Late (31-120 days)         21897

In [10]:
# Filter loan_df for records with "Bad Loan" and "Fully Paid" only

loan_df2 = loan_df[loan_df['loan_status_clean'].isin(['Bad Loan','Fully Paid'])].copy()

print('loan_df shape:',loan_df.shape)
print('loan_df2 shape:',loan_df2.shape)

bad_loan_share = round(len(loan_df2[loan_df2['loan_status_clean']=='Bad Loan']) / len(loan_df2),4)
fully_paid_share = round(len(loan_df2[loan_df2['loan_status_clean']=='Fully Paid']) / len(loan_df2),4)

print('\n')
print('Bad Loan share:',bad_loan_share)
print('Fully Paid share:',fully_paid_share)

loan_df shape: (2260668, 146)
loan_df2 shape: (1306387, 146)


Bad Loan share: 0.2009
Fully Paid share: 0.7991

In [11]:
print(loan_df2.columns)

Index(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade',
       ...
       'hardship_last_payment_amount', 'disbursement_method',
       'debt_settlement_flag', 'debt_settlement_flag_date',
       'settlement_status', 'settlement_date', 'settlement_amount',
       'settlement_percentage', 'settlement_term', 'loan_status_clean'],
      dtype='str', length=146)

### Simple EDA

In [28]:
# Cell 1 — setup and feature list

eda_features = [
    "annual_inc", "dti", "revol_util", "delinq_2yrs", "pub_rec",
    "grade", "sub_grade", "open_acc", "int_rate", "earliest_cr_line",
    "mths_since_last_delinq", "mths_since_last_major_derog",
    "mths_since_last_record", "num_tl_op_past_12m",
    "acc_open_past_24mths", "pub_rec_bankruptcies",
]

numeric_features = loan_df2[eda_features].select_dtypes(include="number").columns.tolist()
numeric_features

['annual_inc',
 'dti',
 'revol_util',
 'delinq_2yrs',
 'pub_rec',
 'open_acc',
 'int_rate',
 'mths_since_last_delinq',
 'mths_since_last_major_derog',
 'mths_since_last_record',
 'num_tl_op_past_12m',
 'acc_open_past_24mths',
 'pub_rec_bankruptcies']

In [29]:
# Cell 2 — missing value audit
missing_summary = pd.DataFrame({
    "missing_count": loan_df2[eda_features].isna().sum(),
    "missing_pct": loan_df2[eda_features].isna().mean() * 100
}).sort_values("missing_pct", ascending=False)

missing_summary

                             missing_count  missing_pct
mths_since_last_record             1083754    82.958113
mths_since_last_major_derog         964008    73.791916
mths_since_last_delinq              659032    50.446920
num_tl_op_past_12m                   70276     5.379417
acc_open_past_24mths                 50030     3.829646
pub_rec_bankruptcies                  1365     0.104487
revol_util                             850     0.065065
dti                                    312     0.023883
pub_rec                                 29     0.002220
delinq_2yrs                             29     0.002220
earliest_cr_line                        29     0.002220
open_acc                                29     0.002220
annual_inc                               4     0.000306
grade                                    0     0.000000
sub_grade                                0     0.000000
int_rate                                 0     0.000000

In [30]:
# Cell 3 — scan for suspicious value concentrations (disguised placeholders)
for col in numeric_features:
    vc = loan_df2[col].value_counts().head(5)
    print(f"--- {col} ---")
    print(vc)
    print()

--- annual_inc ---
annual_inc
60000.0    50517
50000.0    44395
65000.0    37548
70000.0    35853
40000.0    34464
Name: count, dtype: int64

--- dti ---
dti
18.0    961
19.2    958
14.4    934
16.8    926
13.2    894
Name: count, dtype: int64

--- revol_util ---
revol_util
0.0     6781
57.0    2566
54.0    2562
58.0    2555
53.0    2548
Name: count, dtype: int64

--- delinq_2yrs ---
delinq_2yrs
0.0    1054816
1.0     167205
2.0      48946
3.0      17775
4.0       7875
Name: count, dtype: int64

--- pub_rec ---
pub_rec
0.0    1085000
1.0     185347
2.0      23758
3.0       7170
4.0       2533
Name: count, dtype: int64

--- open_acc ---
open_acc
9.0     116023
10.0    113024
8.0     111368
11.0    104447
7.0     100111
Name: count, dtype: int64

--- int_rate ---
int_rate
10.99    37294
11.99    31618
13.99    28731
5.32     26732
9.17     25932
Name: count, dtype: int64

--- mths_since_last_delinq ---
mths_since_last_delinq
12.0    12373
13.0    12347
9.0     12314
6.0     12228
7.0     12068
Name: count, dtype: int64

--- mths_since_last_major_derog ---
mths_since_last_major_derog
45.0    5375
46.0    5345
43.0    5345
40.0    5321
42.0    5313
Name: count, dtype: int64

--- mths_since_last_record ---
mths_since_last_record
71.0    3349
75.0    3307
79.0    3305
72.0    3295
80.0    3286
Name: count, dtype: int64

--- num_tl_op_past_12m ---
num_tl_op_past_12m
1.0    304977
2.0    280214
0.0    207125
3.0    203117
4.0    120342
Name: count, dtype: int64

--- acc_open_past_24mths ---
acc_open_past_24mths
3.0    184285
4.0    176596
2.0    162933
5.0    152713
6.0    121073
Name: count, dtype: int64

--- pub_rec_bankruptcies ---
pub_rec_bankruptcies
0.0    1142116
1.0     153185
2.0       7592
3.0       1539
4.0        381
Name: count, dtype: int64

In [31]:
# Cell 4 — recode confirmed placeholders to true NaN
# EXAMPLE ONLY — replace with whatever you actually find in Cell 3's output
placeholder_map = {
    "annual_inc": [0],          # 0 income is implausible for an approved loan — likely unreported
    # add more columns/values here as you confirm them from Cell 3
}

for col, placeholders in placeholder_map.items():
    loan_df2.loc[loan_df2[col].isin(placeholders), col] = np.nan

loan_df2[list(placeholder_map.keys())].isna().mean() * 100

annual_inc    0.023423
dtype: float64

In [32]:
# Cell 5 — extended percentile view to spot implausible extremes
percentile_view = loan_df2[numeric_features].describe(
    percentiles=[0.01, 0.05, 0.5, 0.95, 0.99, 0.995, 0.999]
).T

percentile_view

                                 count          mean           std   min        1%        5%       50%        95%        99%      99.5%         99.9%          max
annual_inc                   1306081.0  76166.401066  70044.343812  1.00  18000.00  28000.00  65000.00  155000.00  250000.00  321000.00  575000.00000  10999200.00
dti                          1306075.0     18.250236     10.933738 -1.00      1.77      4.98     17.60      32.93      38.37      39.88      64.05926       999.00
revol_util                   1305537.0     51.912379     24.510716  0.00      1.10     10.50     52.30      91.50      98.20      99.50     102.50000       892.30
delinq_2yrs                  1306358.0      0.317456      0.877022  0.00      0.00      0.00      0.00       2.00       4.00       5.00       9.00000        39.00
pub_rec                      1306358.0      0.215289      0.602458  0.00      0.00      0.00      0.00       1.00       2.00       3.00       6.00000        86.00
open_acc                     1306358.0     11.589148      5.466121  0.00      3.00      5.00     11.00      22.00      29.00      32.00      40.00000        90.00
int_rate                     1306387.0     13.259182      4.757423  5.31      5.32      6.62     12.74      22.15      26.30      28.72      30.89000        30.99
mths_since_last_delinq        647355.0     34.303021     21.931669  0.00      1.00      5.00     31.00      74.00      80.00      81.00      92.00000       226.00
mths_since_last_major_derog   342379.0     43.686146     21.370791  0.00      3.00      9.00     44.00      77.00      82.00      89.00     110.00000       226.00
mths_since_last_record        222633.0     70.435061     26.829176  0.00      5.00     23.00     71.00     113.00     118.00     118.00     119.00000       129.00
num_tl_op_past_12m           1236111.0      2.181200      1.844205  0.00      0.00      0.00      2.00       5.00       8.00       9.00      13.00000        32.00
acc_open_past_24mths         1256357.0      4.696506      3.185180  0.00      0.00      1.00      4.00      11.00      15.00      17.00      22.00000        64.00
pub_rec_bankruptcies         1305022.0      0.134617      0.378144  0.00      0.00      0.00      0.00       1.00       1.00       2.00       3.00000        12.00

In [34]:
# Cell 6 — flag implausible values based on domain logic (adjust thresholds after reviewing Cell 5)
implausible_rules = {
    "dti": lambda x: (x < 0) | (x > 100),
    "revol_util": lambda x: (x < 0) | (x > 150),   # can exceed 100% technically, but not by a huge margin
    "annual_inc": lambda x: x < 0,
    "open_acc": lambda x: x < 0,
}

flag_summary = {}
for col, rule in implausible_rules.items():
    flagged = rule(loan_df2[col])
    flag_summary[col] = flagged.sum()
    loan_df2.loc[flagged, col] = np.nan   # convert confirmed-impossible values to true missing, not a guessed number

pd.Series(flag_summary, name="n_flagged_and_nulled")

dti           478
revol_util     19
annual_inc      0
open_acc        0
Name: n_flagged_and_nulled, dtype: int64

In [36]:
# Cell 7 — final missing value picture after cleaning
final_missing = pd.DataFrame({
    "missing_count": loan_df2[eda_features].isna().sum(),
    "missing_pct": loan_df2[eda_features].isna().mean() * 100
}).sort_values("missing_pct", ascending=False)

final_missing

                             missing_count  missing_pct
mths_since_last_record             1083754    82.958113
mths_since_last_major_derog         964008    73.791916
mths_since_last_delinq              659032    50.446920
num_tl_op_past_12m                   70276     5.379417
acc_open_past_24mths                 50030     3.829646
pub_rec_bankruptcies                  1365     0.104487
revol_util                             869     0.066519
dti                                    790     0.060472
annual_inc                             306     0.023423
delinq_2yrs                             29     0.002220
open_acc                                29     0.002220
pub_rec                                 29     0.002220
earliest_cr_line                        29     0.002220
grade                                    0     0.000000
sub_grade                                0     0.000000
int_rate                                 0     0.000000

In [37]:
# Cell 8 — apply cleaning rules based on the percentile findings above

# dti: -1 is impossible (ratio can't be negative), 999 is a disguised placeholder
loan_df2.loc[loan_df2["dti"] < 0, "dti"] = np.nan
loan_df2.loc[loan_df2["dti"] == 999, "dti"] = np.nan

# annual_inc: $1 is implausible for an approved loan
loan_df2.loc[loan_df2["annual_inc"] <= 1, "annual_inc"] = np.nan

# annual_inc: extreme high-end outliers — cap at 99.9th percentile rather than deleting,
# since some legitimately high earners exist, we just don't want a $11M entry distorting bins
inc_cap = loan_df2["annual_inc"].quantile(0.999)
loan_df2.loc[loan_df2["annual_inc"] > inc_cap, "annual_inc"] = inc_cap

# revol_util: cap unrealistic extremes rather than nulling entirely
util_cap = loan_df2["revol_util"].quantile(0.999)
loan_df2.loc[loan_df2["revol_util"] > util_cap, "revol_util"] = util_cap

# pub_rec and pub_rec_bankruptcies: flag extreme tail as suspicious, cap at 99.9th percentile
for col in ["pub_rec", "pub_rec_bankruptcies"]:
    cap = loan_df2[col].quantile(0.999)
    loan_df2.loc[loan_df2[col] > cap, col] = cap

loan_df2[["dti", "annual_inc", "revol_util", "pub_rec", "pub_rec_bankruptcies"]].describe()

                dti    annual_inc    revol_util       pub_rec  pub_rec_bankruptcies
count  1.305597e+06  1.306072e+06  1.305518e+06  1.306358e+06          1.305022e+06
mean   1.816043e+01  7.561300e+04  5.190454e+01  2.132494e-01          1.339104e-01
std    8.648072e+00  4.877512e+04  2.448188e+01  5.563530e-01          3.706776e-01
min    0.000000e+00  2.000000e+00  0.000000e+00  0.000000e+00          0.000000e+00
25%    1.178000e+01  4.580000e+04  3.360000e+01  0.000000e+00          0.000000e+00
50%    1.760000e+01  6.500000e+04  5.230000e+01  0.000000e+00          0.000000e+00
75%    2.402000e+01  9.000000e+04  7.080000e+01  0.000000e+00          0.000000e+00
max    1.000000e+02  5.750000e+05  1.025000e+02  6.000000e+00          3.000000e+00

### IV/WOE test

In [15]:
from optbinning import BinningProcess

In [38]:
# Cell 4 — time-based split using issue_d (train only, per your OOT strategy)
loan_df2["issue_d"] = pd.to_datetime(loan_df2["issue_d"], format="%b-%Y")

train = loan_df2[loan_df2["issue_d"].dt.year <= 2016].copy()
val   = loan_df2[loan_df2["issue_d"].dt.year == 2017].copy()
test  = loan_df2[loan_df2["issue_d"].dt.year == 2018].copy()

train.shape, val.shape, test.shape

((1100286, 147), (158910, 147), (47191, 147))

In [39]:
# Cell 5 — leaked / post-origination columns to exclude before IV screening
# These describe what happened AFTER the loan was funded, or are identifiers/targets

leaked_cols = [
    # payment history / outcome of this loan
    "out_prncp", "out_prncp_inv", "total_pymnt", "total_pymnt_inv",
    "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee",
    "last_pymnt_d", "last_pymnt_amnt", "next_pymnt_d",
    "last_credit_pull_d", "last_fico_range_high", "last_fico_range_low",

    # target-derived / redundant target info
    "loan_status", "loan_status_clean",

    # hardship / settlement programs (only exist post-origination, post-distress)
    "hardship_flag", "hardship_type", "hardship_reason", "hardship_status",
    "deferral_term", "hardship_amount", "hardship_start_date", "hardship_end_date",
    "payment_plan_start_date", "hardship_length", "hardship_dpd",
    "hardship_loan_status", "orig_projected_additional_accrued_interest",
    "hardship_payoff_balance_amount", "hardship_last_payment_amount",
    "debt_settlement_flag", "debt_settlement_flag_date",
    "settlement_status", "settlement_date", "settlement_amount",
    "settlement_percentage", "settlement_term",

    # identifiers, free text, non-predictive
    "id", "member_id", "url", "desc", "emp_title", "title", "zip_code",

    # not a feature for modeling — used only for the time split
    "issue_d",

    # policy code — constant / not a real predictor
    "policy_code",
]

# drop only the ones actually present in this dataset version
leaked_cols_present = [c for c in leaked_cols if c in train.columns]
leaked_cols_present

['out_prncp',
 'out_prncp_inv',
 'total_pymnt',
 'total_pymnt_inv',
 'total_rec_prncp',
 'total_rec_int',
 'total_rec_late_fee',
 'recoveries',
 'collection_recovery_fee',
 'last_pymnt_d',
 'last_pymnt_amnt',
 'next_pymnt_d',
 'last_credit_pull_d',
 'loan_status',
 'loan_status_clean',
 'hardship_flag',
 'hardship_type',
 'hardship_reason',
 'hardship_status',
 'deferral_term',
 'hardship_amount',
 'hardship_start_date',
 'hardship_end_date',
 'payment_plan_start_date',
 'hardship_length',
 'hardship_dpd',
 'hardship_loan_status',
 'orig_projected_additional_accrued_interest',
 'hardship_payoff_balance_amount',
 'hardship_last_payment_amount',
 'debt_settlement_flag',
 'debt_settlement_flag_date',
 'settlement_status',
 'settlement_date',
 'settlement_amount',
 'settlement_percentage',
 'settlement_term',
 'id',
 'member_id',
 'url',
 'desc',
 'emp_title',
 'title',
 'zip_code',
 'issue_d',
 'policy_code']

In [40]:
# Cell 6 — build the feature list: everything except target + leaked columns
exclude = leaked_cols_present + ["target"]
feature_cols = [c for c in train.columns if c not in exclude]

X_train = train[feature_cols]
y_train = train["target"].values

len(feature_cols)

100

In [41]:
# Cell 7 — run IV/WOE screening with optbinning's BinningProcess
# This automatically handles missing values as their own bin, per feature type

# split numeric vs categorical for optbinning
numeric_cols = X_train.select_dtypes(include=["number"]).columns.tolist()
categorical_cols = X_train.select_dtypes(include=["object"]).columns.tolist()

C:\Users\hexs2\AppData\Local\Temp\ipykernel_26264\2311565866.py:6: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = X_train.select_dtypes(include=["object"]).columns.tolist()

In [42]:
# Cell 1 — find the offending columns
import numpy as np
import pandas as pd

diag = pd.DataFrame({
    "n_non_null": X_train.notna().sum(),
    "pct_missing": X_train.isna().mean().round(4),
    "n_unique": X_train.nunique(dropna=True),
})

# columns optbinning cannot fit at all
empty_cols = diag.index[diag["n_non_null"] == 0].tolist()

# columns that will fit but are effectively useless
constant_cols = diag.index[(diag["n_unique"] <= 1) & (diag["n_non_null"] > 0)].tolist()

print("100% missing in train:", empty_cols)
print("Constant in train:", constant_cols)
diag.sort_values("pct_missing", ascending=False).head(25)

100% missing in train: ['revol_bal_joint', 'sec_app_earliest_cr_line', 'sec_app_inq_last_6mths', 'sec_app_mort_acc', 'sec_app_open_acc', 'sec_app_revol_util', 'sec_app_open_act_il', 'sec_app_num_rev_accts', 'sec_app_chargeoff_within_12_mths', 'sec_app_collections_12_mths_ex_med', 'sec_app_mths_since_last_major_derog']
Constant in train: ['pymnt_plan', 'verification_status_joint']

                                     n_non_null  pct_missing  n_unique
revol_bal_joint                               0       1.0000         0
sec_app_mths_since_last_major_derog           0       1.0000         0
sec_app_collections_12_mths_ex_med            0       1.0000         0
sec_app_chargeoff_within_12_mths              0       1.0000         0
sec_app_inq_last_6mths                        0       1.0000         0
sec_app_earliest_cr_line                      0       1.0000         0
sec_app_mort_acc                              0       1.0000         0
sec_app_num_rev_accts                         0       1.0000         0
sec_app_open_act_il                           0       1.0000         0
sec_app_open_acc                              0       1.0000         0
sec_app_revol_util                            0       1.0000         0
dti_joint                                  5307       0.9952      2362
verification_status_joint                  5309       0.9952         1
annual_inc_joint                           5309       0.9952      1521
mths_since_last_record                   184468       0.8323       123
il_util                                  255929       0.7674       217
mths_since_recent_bc_dlq                 262205       0.7617       162
mths_since_rcnt_il                       286095       0.7400       307
mths_since_last_major_derog              286976       0.7392       167
open_il_24m                              293475       0.7333        31
open_acc_6m                              293474       0.7333        19
total_bal_il                             293475       0.7333     94390
open_il_12m                              293475       0.7333        18
inq_last_12m                             293474       0.7333        37
inq_fi                                   293475       0.7333        29

In [43]:
# Cell 2 — catch the sneakier cases (inf values, empty-string categoricals)
num_cols = X_train.select_dtypes(include=[np.number]).columns
all_inf = [c for c in num_cols
           if X_train[c].notna().sum() > 0
           and not np.isfinite(X_train[c].dropna()).any()]

obj_cols = X_train.select_dtypes(include=["object", "category"]).columns
blank_cols = [c for c in obj_cols
              if X_train[c].astype(str).str.strip()
                          .replace({"": np.nan, "nan": np.nan, "None": np.nan})
                          .notna().sum() == 0]

print("All-inf:", all_inf)
print("Blank-only categoricals:", blank_cols)

C:\Users\hexs2\AppData\Local\Temp\ipykernel_26264\2302291586.py:7: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols = X_train.select_dtypes(include=["object", "category"]).columns

All-inf: []
Blank-only categoricals: ['sec_app_earliest_cr_line']

In [44]:
# Cell 3 — drop and refit
drop_cols = sorted(set(empty_cols + constant_cols + all_inf + blank_cols))

feature_cols_clean = [c for c in feature_cols if c not in drop_cols]
categorical_cols_clean = [c for c in categorical_cols if c not in drop_cols]

print(f"Dropping {len(drop_cols)} columns, {len(feature_cols_clean)} remain")

binning_process = BinningProcess(
    variable_names=feature_cols_clean,
    categorical_variables=categorical_cols_clean,
)
binning_process.fit(X_train[feature_cols_clean], y_train)

Dropping 13 columns, 87 remain

BinningProcess(categorical_variables=['term', 'grade', 'sub_grade',
                                      'emp_length', 'home_ownership',
                                      'verification_status', 'purpose',
                                      'addr_state', 'earliest_cr_line',
                                      'initial_list_status', 'application_type',
                                      'disbursement_method'],
               variable_names=['loan_amnt', 'funded_amnt', 'funded_amnt_inv',
                               'term', 'int_rate', 'installment', 'grade',
                               'sub_grade', 'emp_length', 'h...ip',
                               'annual_inc', 'verification_status', 'purpose',
                               'addr_state', 'dti', 'delinq_2yrs',
                               'earliest_cr_line', 'inq_last_6mths',
                               'mths_since_last_delinq',
                               'mths_since_last_record', 'open_acc', 'pub_rec',
                               'revol_bal', 'revol_util', 'total_acc',
                               'initial_list_status',
                               'collections_12_mths_ex_med',
                               'mths_since_last_major_derog',
                               'application_type', 'annual_inc_joint', ...])

In [45]:
# Cell 7 — IV/WOE screening with optbinning's BinningProcess
# Fitted on the TRAINING SPLIT ONLY — no temporal leakage into feature selection.
# optbinning handles missing values as their own bin per feature.

# derive categoricals from the cleaned feature list, not from raw X_train
categorical_cols_clean = (
    X_train[feature_cols_clean]
    .select_dtypes(include=["object", "category", "bool"])
    .columns.tolist()
)

print(f"Features: {len(feature_cols_clean)}  |  Categorical: {len(categorical_cols_clean)}")

binning_process = BinningProcess(
    variable_names=feature_cols_clean,
    categorical_variables=categorical_cols_clean,
)

binning_process.fit(X_train[feature_cols_clean], y_train)

C:\Users\hexs2\AppData\Local\Temp\ipykernel_26264\509274721.py:8: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  .select_dtypes(include=["object", "category", "bool"])

Features: 87  |  Categorical: 12

BinningProcess(categorical_variables=['term', 'grade', 'sub_grade',
                                      'emp_length', 'home_ownership',
                                      'verification_status', 'purpose',
                                      'addr_state', 'earliest_cr_line',
                                      'initial_list_status', 'application_type',
                                      'disbursement_method'],
               variable_names=['loan_amnt', 'funded_amnt', 'funded_amnt_inv',
                               'term', 'int_rate', 'installment', 'grade',
                               'sub_grade', 'emp_length', 'h...ip',
                               'annual_inc', 'verification_status', 'purpose',
                               'addr_state', 'dti', 'delinq_2yrs',
                               'earliest_cr_line', 'inq_last_6mths',
                               'mths_since_last_delinq',
                               'mths_since_last_record', 'open_acc', 'pub_rec',
                               'revol_bal', 'revol_util', 'total_acc',
                               'initial_list_status',
                               'collections_12_mths_ex_med',
                               'mths_since_last_major_derog',
                               'application_type', 'annual_inc_joint', ...])

In [46]:
# Cell 8 — inspect the binning summary
summary = binning_process.summary().sort_values("iv", ascending=False)
summary.head(30)

                     name        dtype   status  selected n_bins        iv        js      gini quality_score
7               sub_grade  categorical  OPTIMAL      True     15  0.493045  0.058283  0.379064       0.93285
4                int_rate    numerical  OPTIMAL      True     13  0.466804  0.055169  0.367367       0.94452
6                   grade  categorical  OPTIMAL      True      5  0.461965  0.055096  0.361831      0.877571
3                    term  categorical  OPTIMAL      True      2  0.194665  0.023975  0.199209      0.349357
49   acc_open_past_24mths    numerical  OPTIMAL      True      9  0.082744  0.010266  0.162726      0.330147
14                    dti    numerical  OPTIMAL      True     16  0.078904  0.009792  0.158976      0.228442
77     num_tl_op_past_12m    numerical  OPTIMAL      True      6  0.061737  0.007677  0.139746      0.241433
51         bc_open_to_buy    numerical  OPTIMAL      True     13  0.057234  0.007091  0.127446      0.181093
50            avg_cur_bal    numerical  OPTIMAL      True     14  0.053835  0.006685  0.123163      0.125123
11    verification_status  categorical  OPTIMAL      True      3  0.052558   0.00654  0.115064      0.179725
82        tot_hi_cred_lim    numerical  OPTIMAL      True     11  0.046921  0.005838  0.114525      0.105409
84         total_bc_limit    numerical  OPTIMAL      True     14  0.043876  0.005452  0.112452      0.095966
33            tot_cur_bal    numerical  OPTIMAL      True     13  0.042532  0.005295   0.11468       0.16852
58         mo_sin_rcnt_tl    numerical  OPTIMAL      True     12   0.04186  0.005209  0.114363      0.153301
59               mort_acc    numerical  OPTIMAL      True      6  0.039187  0.004884  0.109116      0.144657
62  mths_since_recent_inq    numerical  OPTIMAL      True     12  0.038477  0.004793   0.11053      0.033487
42            open_rv_24m    numerical  OPTIMAL      True      4  0.037645  0.004666   0.07875      0.083163
44               all_util    numerical  OPTIMAL      True      4  0.035441  0.004403  0.077769      0.078253
57  mo_sin_rcnt_rev_tl_op    numerical  OPTIMAL      True     13  0.033827  0.004212  0.100942      0.029908
66        num_actv_rev_tl    numerical  OPTIMAL      True      9  0.033761  0.004205  0.103231       0.13744
72    num_rev_tl_bal_gt_0    numerical  OPTIMAL      True      9  0.033323   0.00415  0.102258      0.135206
1             funded_amnt    numerical  OPTIMAL      True      8  0.032291  0.004027  0.099446      0.122629
0               loan_amnt    numerical  OPTIMAL      True      8  0.032266  0.004024  0.099411      0.122982
45       total_rev_hi_lim    numerical  OPTIMAL      True     11   0.03181  0.003958  0.091668      0.065321
41            open_rv_12m    numerical  OPTIMAL      True      4   0.03171  0.003938  0.076331      0.070085
2         funded_amnt_inv    numerical  OPTIMAL      True      8  0.031605  0.003942  0.098488      0.120574
60   mths_since_recent_bc    numerical  OPTIMAL      True     11  0.031176  0.003884  0.097742       0.11036
10             annual_inc    numerical  OPTIMAL      True     13  0.031043  0.003869  0.098533      0.111413
34            open_acc_6m    numerical  OPTIMAL      True      3  0.030784  0.003825  0.075728      0.070021
48           inq_last_12m    numerical  OPTIMAL      True      3   0.03076  0.003825  0.075745      0.069885

In [49]:
print(summary.shape)
print(summary[summary['iv']>=0.02].shape)

(87, 9)
(47, 9)

In [ ]:
# Cell 9 (corrected) — filter your summary table to the 47 columns with IV >= 0.02
iv_results = summary[summary["iv"] >= 0.02]
iv_results.shape   # should show 47 rows

# Cell 10 — find which of the 47 columns still haven't been checked
selected_47 = summary["name"].tolist()   # your 47 columns with IV >= 0.02
already_cleaned = ["annual_inc", "dti", "revol_util", "pub_rec", "pub_rec_bankruptcies"]

not_yet_checked = [c for c in selected_47 if c not in already_cleaned]
print(f"{len(not_yet_checked)} of {len(selected_47)} columns still need the EDA pass:")
print(not_yet_checked)

82 of 87 columns still need the EDA pass:
['sub_grade', 'int_rate', 'grade', 'term', 'acc_open_past_24mths', 'num_tl_op_past_12m', 'bc_open_to_buy', 'avg_cur_bal', 'verification_status', 'tot_hi_cred_lim', 'total_bc_limit', 'tot_cur_bal', 'mo_sin_rcnt_tl', 'mort_acc', 'mths_since_recent_inq', 'open_rv_24m', 'all_util', 'mo_sin_rcnt_rev_tl_op', 'num_actv_rev_tl', 'num_rev_tl_bal_gt_0', 'funded_amnt', 'loan_amnt', 'total_rev_hi_lim', 'open_rv_12m', 'funded_amnt_inv', 'mths_since_recent_bc', 'open_acc_6m', 'inq_last_12m', 'open_il_12m', 'open_il_24m', 'percent_bc_gt_75', 'mths_since_rcnt_il', 'installment', 'il_util', 'mo_sin_old_rev_tl_op', 'max_bal_bc', 'bc_util', 'home_ownership', 'inq_last_6mths', 'inq_fi', 'open_act_il', 'total_bal_il', 'total_cu_tl', 'earliest_cr_line', 'purpose', 'addr_state', 'num_actv_bc_tl', 'num_op_rev_tl', 'num_sats', 'mo_sin_old_il_acct', 'emp_length', 'total_il_high_credit_limit', 'num_accts_ever_120_pd', 'tot_coll_amt', 'open_acc', 'total_bal_ex_mort', 'mths_since_last_record', 'num_bc_tl', 'num_bc_sats', 'pct_tl_nvr_dlq', 'num_il_tl', 'num_tl_90g_dpd_24m', 'mths_since_last_major_derog', 'num_rev_accts', 'num_tl_30dpd', 'revol_bal', 'mths_since_last_delinq', 'delinq_2yrs', 'mths_since_recent_bc_dlq', 'mths_since_recent_revol_delinq', 'initial_list_status', 'total_acc', 'dti_joint', 'annual_inc_joint', 'num_tl_120dpd_2m', 'tax_liens', 'delinq_amnt', 'acc_now_delinq', 'chargeoff_within_12_mths', 'collections_12_mths_ex_med', 'application_type', 'disbursement_method']

In [53]:
# Cell 11 (corrected) — find which of the 47 still need the EDA/cleaning pass
selected_47 = iv_results["name"].tolist()
already_cleaned = ["annual_inc", "dti", "revol_util", "pub_rec", "pub_rec_bankruptcies"]

not_yet_checked = [c for c in selected_47 if c not in already_cleaned]
print(f"{len(not_yet_checked)} of {len(selected_47)} columns still need the EDA pass:")
print(not_yet_checked)

44 of 47 columns still need the EDA pass:
['sub_grade', 'int_rate', 'grade', 'term', 'acc_open_past_24mths', 'num_tl_op_past_12m', 'bc_open_to_buy', 'avg_cur_bal', 'verification_status', 'tot_hi_cred_lim', 'total_bc_limit', 'tot_cur_bal', 'mo_sin_rcnt_tl', 'mort_acc', 'mths_since_recent_inq', 'open_rv_24m', 'all_util', 'mo_sin_rcnt_rev_tl_op', 'num_actv_rev_tl', 'num_rev_tl_bal_gt_0', 'funded_amnt', 'loan_amnt', 'total_rev_hi_lim', 'open_rv_12m', 'funded_amnt_inv', 'mths_since_recent_bc', 'open_acc_6m', 'inq_last_12m', 'open_il_12m', 'open_il_24m', 'percent_bc_gt_75', 'mths_since_rcnt_il', 'installment', 'il_util', 'mo_sin_old_rev_tl_op', 'max_bal_bc', 'bc_util', 'home_ownership', 'inq_last_6mths', 'inq_fi', 'open_act_il', 'total_bal_il', 'total_cu_tl', 'earliest_cr_line']

In [54]:
# Cell 12 — split the remaining columns by dtype so we apply the right check to each
not_yet_checked = ['sub_grade', 'int_rate', 'grade', 'term', 'acc_open_past_24mths',
    'num_tl_op_past_12m', 'bc_open_to_buy', 'avg_cur_bal', 'verification_status',
    'tot_hi_cred_lim', 'total_bc_limit', 'tot_cur_bal', 'mo_sin_rcnt_tl', 'mort_acc',
    'mths_since_recent_inq', 'open_rv_24m', 'all_util', 'mo_sin_rcnt_rev_tl_op',
    'num_actv_rev_tl', 'num_rev_tl_bal_gt_0', 'funded_amnt', 'loan_amnt',
    'total_rev_hi_lim', 'open_rv_12m', 'funded_amnt_inv', 'mths_since_recent_bc',
    'open_acc_6m', 'inq_last_12m', 'open_il_12m', 'open_il_24m', 'percent_bc_gt_75',
    'mths_since_rcnt_il', 'installment', 'il_util', 'mo_sin_old_rev_tl_op',
    'max_bal_bc', 'bc_util', 'home_ownership', 'inq_last_6mths', 'inq_fi',
    'open_act_il', 'total_bal_il', 'total_cu_tl', 'earliest_cr_line']

date_cols = ["earliest_cr_line"]
categorical_cols = ["sub_grade", "grade", "term", "verification_status", "home_ownership"]
numeric_cols = [c for c in not_yet_checked if c not in date_cols + categorical_cols]

print(f"Numeric: {len(numeric_cols)}")
print(f"Categorical: {len(categorical_cols)}")
print(f"Date: {len(date_cols)}")

Numeric: 38
Categorical: 5
Date: 1

In [56]:
# Cell 13 — missing value audit for the numeric group
missing_summary_47 = pd.DataFrame({
    "missing_count": loan_df2[numeric_cols].isna().sum(),
    "missing_pct": loan_df2[numeric_cols].isna().mean() * 100
}).sort_values("missing_pct", ascending=False)

missing_summary_47

                       missing_count  missing_pct
il_util                       873692    66.878498
mths_since_rcnt_il            819808    62.753839
all_util                      806862    61.762862
open_acc_6m                   806812    61.759035
total_cu_tl                   806812    61.759035
inq_last_12m                  806812    61.759035
open_il_12m                   806811    61.758958
max_bal_bc                    806811    61.758958
open_il_24m                   806811    61.758958
total_bal_il                  806811    61.758958
open_act_il                   806811    61.758958
inq_fi                        806811    61.758958
open_rv_12m                   806811    61.758958
open_rv_24m                   806811    61.758958
mths_since_recent_inq         172301    13.189124
avg_cur_bal                    70297     5.381024
mo_sin_old_rev_tl_op           70277     5.379493
mo_sin_rcnt_rev_tl_op          70277     5.379493
num_tl_op_past_12m             70276     5.379417
tot_cur_bal                    70276     5.379417
mo_sin_rcnt_tl                 70276     5.379417
tot_hi_cred_lim                70276     5.379417
num_rev_tl_bal_gt_0            70276     5.379417
total_rev_hi_lim               70276     5.379417
num_actv_rev_tl                70276     5.379417
bc_util                        64136     4.909418
percent_bc_gt_75               63797     4.883469
bc_open_to_buy                 63389     4.852238
mths_since_recent_bc           62491     4.783498
acc_open_past_24mths           50030     3.829646
total_bc_limit                 50030     3.829646
mort_acc                       50030     3.829646
inq_last_6mths                    30     0.002296
int_rate                           0     0.000000
funded_amnt_inv                    0     0.000000
loan_amnt                          0     0.000000
funded_amnt                        0     0.000000
installment                        0     0.000000

In [57]:
# Cell 14 — extended percentile view to spot implausible extremes
percentile_view_47 = loan_df2[numeric_cols].describe(
    percentiles=[0.01, 0.05, 0.5, 0.95, 0.99, 0.995, 0.999]
).T

percentile_view_47

                           count           mean            std     min         1%        5%        50%        95%        99%       99.5%        99.9%         max
int_rate               1306387.0      13.259182       4.757423    5.31     5.3200      6.62      12.74      22.15      26.30      28.720       30.890       30.99
acc_open_past_24mths   1256357.0       4.696506       3.185180    0.00     0.0000      1.00       4.00      11.00      15.00      17.000       22.000       64.00
num_tl_op_past_12m     1236111.0       2.181200       1.844205    0.00     0.0000      0.00       2.00       5.00       8.00       9.000       13.000       32.00
bc_open_to_buy         1242998.0   10125.204000   15277.633097    0.00     0.0000    131.00    4662.00   38798.15   73865.03   90838.090   134027.006   559912.00
avg_cur_bal            1236090.0   13487.675459   16280.814986    0.00   466.0000   1102.00    7416.00   43013.00   73420.00   90077.000   142148.021   958084.00
tot_hi_cred_lim        1236111.0  174211.061067  177653.652911    0.00  8600.0000  18843.00  112391.00  497392.00  765426.10  912791.200  1389645.380  9999999.00
total_bc_limit         1256357.0   21566.236091   21478.803245    0.00     0.0000   2300.00   15000.00   62900.00  103300.00  122500.000   169964.400  1105500.00
tot_cur_bal            1236111.0  141079.599877  157311.421815    0.00  3125.0000   8653.00   80335.00  432981.50  672919.70  804269.250  1229727.040  8000078.00
mo_sin_rcnt_tl         1236111.0       7.841850       8.708850    0.00     0.0000      1.00       5.00      22.00      43.00      56.000       88.000      314.00
mort_acc               1256357.0       1.676858       2.005043    0.00     0.0000      0.00       1.00       6.00       8.00       9.000       12.000       51.00
mths_since_recent_inq  1134086.0       6.703446       5.847065    0.00     0.0000      0.00       5.00      19.00      23.00      23.000       24.000       25.00
open_rv_24m             499576.0       3.020225       2.707107    0.00     0.0000      0.00       2.00       8.00      12.00      14.000       19.000       53.00
all_util                499525.0      58.231678      20.924820    0.00     7.0000     21.00      60.00      90.00     102.00     108.000      123.000      198.00
mo_sin_rcnt_rev_tl_op  1236110.0      13.086486      16.290537    0.00     0.0000      1.00       8.00      43.00      84.00      99.000      133.000      438.00
num_actv_rev_tl        1236111.0       5.646059       3.297208    0.00     1.0000      2.00       5.00      12.00      17.00      19.000       24.000       63.00
num_rev_tl_bal_gt_0    1236111.0       5.595712       3.211497    0.00     1.0000      2.00       5.00      12.00      16.00      18.000       23.000       45.00
funded_amnt            1306387.0   14396.430154    8694.589186  500.00  1500.0000   3200.00   12000.00   32500.00   35000.00   38025.000    40000.000    40000.00
loan_amnt              1306387.0   14405.523421    8698.613361  500.00  1500.0000   3200.00   12000.00   32525.00   35000.00   38025.000    40000.000    40000.00
total_rev_hi_lim       1236111.0   32707.968708   36643.929445    0.00  2800.0000   6000.00   24000.00   85600.00  156600.00  201600.000   341889.000  9999999.00
open_rv_12m             499576.0       1.428167       1.578944    0.00     0.0000      0.00       1.00       4.00       7.00       8.000       11.000       28.00
funded_amnt_inv        1306387.0   14368.097881    8700.952295    0.00  1500.0000   3100.00   12000.00   32500.00   35000.00   38025.000    40000.000    40000.00
mths_since_recent_bc   1243896.0      23.790031      30.663717    0.00     1.0000      2.00      13.00      86.00     144.00     174.000      269.000      639.00
open_acc_6m             499575.0       1.057285       1.212553    0.00     0.0000      0.00       1.00       3.00       5.00       6.000        8.000       18.00
inq_last_12m            499575.0       2.329876       2.552782    0.00     0.0000      0.00       2.00       7.00      12.00      14.000       19.000       67.00
open_il_12m             499576.0       0.783921       0.997665    0.00     0.0000      0.00       1.00       3.00       4.00       5.000        6.000       25.00
open_il_24m             499576.0       1.757346       1.692169    0.00     0.0000      0.00       1.00       5.00       7.00       9.000       12.000       51.00
percent_bc_gt_75       1242590.0      45.318736      35.990071    0.00     0.0000      0.00      44.40     100.00     100.00     100.000      100.000      100.00
mths_since_rcnt_il      486579.0      19.417431      24.678115    0.00     1.0000      2.00      12.00      68.00     128.00     146.000      191.000      511.00
installment            1306387.0     437.778725     261.047148    4.93    52.8886    108.65     375.43     961.23    1218.61    1265.160     1368.660     1719.83
il_util                 432695.0      71.543854      22.839366    0.00     6.0000     29.00      75.00     101.00     119.00     128.000      150.000      558.00
mo_sin_old_rev_tl_op   1236110.0     181.498129      94.335748    2.00    29.0000     53.00     164.00     363.00     472.00     515.000      595.000      852.00
max_bal_bc              499576.0    5527.685898    5474.736275    0.00     0.0000    306.00    4197.00   15491.00   24354.00   28362.500    41366.800   776843.00
bc_util                1242251.0      60.071391      28.260079    0.00     0.0000      8.90      63.40      98.00     100.90     102.000      108.600      339.60
inq_last_6mths         1306357.0       0.666479       0.964014    0.00     0.0000      0.00       0.00       3.00       4.00       5.000        6.000       33.00
inq_fi                  499576.0       1.099468       1.591615    0.00     0.0000      0.00       1.00       4.00       7.00       8.000       12.000       48.00
open_act_il             499576.0       2.797732       2.990804    0.00     0.0000      0.00       2.00       9.00      15.00      18.000       24.000       57.00
total_bal_il            499576.0   35982.154599   42888.918310    0.00     0.0000      0.00   24208.00  112209.00  204926.50  253769.875   385394.900  1711009.00
total_cu_tl             499575.0       1.623424       2.838507    0.00     0.0000      0.00       0.00       7.00      13.00      16.000       23.000       79.00

In [58]:
# Cell 15 — value counts for each categorical column
for col in categorical_cols:
    print(f"--- {col} ---")
    print(loan_df2[col].value_counts(dropna=False))
    print()

--- sub_grade ---
sub_grade
C1    82938
B4    80683
B5    79680
B3    79498
C2    76997
C3    72864
C4    72243
B2    71746
B1    68905
C5    65524
A5    62119
A4    50538
D1    50072
D2    43616
A1    41261
D3    38327
A3    36613
A2    35812
D4    34721
D5    29243
E1    23339
E2    21093
E3    18070
E4    15471
E5    14137
F1     9829
F2     7121
F3     6041
F4     4825
F5     3916
G1     2955
G2     2128
G3     1623
G4     1301
G5     1138
Name: count, dtype: int64

--- grade ---
grade
B    380512
C    370566
A    226343
D    195979
E     92110
F     31732
G      9145
Name: count, dtype: int64

--- term ---
term
36 months    991212
60 months    315175
Name: count, dtype: int64

--- verification_status ---
verification_status
Source Verified    504027
Verified           408316
Not Verified       394044
Name: count, dtype: int64

--- home_ownership ---
home_ownership
MORTGAGE    646765
RENT        519084
OWN         140036
ANY            267
OTHER          182
NONE            53
Name: count, dtype: int64

In [59]:
# Cell 16 — date logic check for earliest_cr_line
loan_df2["earliest_cr_line"] = pd.to_datetime(loan_df2["earliest_cr_line"], format="%b-%Y")

# credit history should have started BEFORE the loan was issued — flag if not
bad_date_logic = loan_df2["earliest_cr_line"] > loan_df2["issue_d"]
print(f"Rows where earliest_cr_line is AFTER issue_d: {bad_date_logic.sum()}")

# also check for implausibly old dates (e.g. before 1950, likely a data entry error)
too_old = loan_df2["earliest_cr_line"].dt.year < 1950
print(f"Rows with earliest_cr_line before 1950: {too_old.sum()}")

loan_df2["earliest_cr_line"].describe()

Rows where earliest_cr_line is AFTER issue_d: 0
Rows with earliest_cr_line before 1950: 9

count                       1306358
mean     1999-02-15 11:59:34.073875
min             1934-04-01 00:00:00
25%             1995-04-01 00:00:00
50%             2000-07-01 00:00:00
75%             2004-06-01 00:00:00
max             2015-09-01 00:00:00
Name: earliest_cr_line, dtype: object

In [60]:
# Cell 17 — check whether missingness in the 61.76% cluster aligns with issue year
cluster_61 = ["il_util", "mths_since_rcnt_il", "all_util", "open_acc_6m", "total_cu_tl",
              "inq_last_12m", "open_il_12m", "max_bal_bc", "open_il_24m", "total_bal_il",
              "open_act_il", "inq_fi", "open_rv_12m", "open_rv_24m"]

loan_df2["issue_year"] = loan_df2["issue_d"].dt.year
loan_df2.groupby("issue_year")[cluster_61[0]].apply(lambda x: x.isna().mean() * 100)

issue_year
2007    100.000000
2008    100.000000
2009    100.000000
2010    100.000000
2011    100.000000
2012    100.000000
2013    100.000000
2014    100.000000
2015     95.621458
2016     12.788713
2017     13.522119
2018     16.628171
Name: il_util, dtype: float64

In [61]:
# Cell 18 — fix disguised placeholders
for col in ["tot_hi_cred_lim", "total_rev_hi_lim"]:
    loan_df2.loc[loan_df2[col] == 9999999, col] = np.nan

# Cell 18 (cont.) — cap extreme outliers at the 99.9th percentile
cap_cols = ["bc_util", "il_util", "mo_sin_old_rev_tl_op", "mths_since_recent_bc",
            "mort_acc", "tot_cur_bal", "avg_cur_bal", "total_bal_il",
            "num_tl_op_past_12m", "acc_open_past_24mths", "bc_open_to_buy"]

for col in cap_cols:
    cap = loan_df2[col].quantile(0.999)
    loan_df2.loc[loan_df2[col] > cap, col] = cap

# Cell 18 (cont.) — fix implausible earliest_cr_line entries
loan_df2.loc[loan_df2["earliest_cr_line"].dt.year < 1950, "earliest_cr_line"] = pd.NaT

loan_df2[["tot_hi_cred_lim", "total_rev_hi_lim", "bc_util", "il_util", "earliest_cr_line"]].describe()

       tot_hi_cred_lim  total_rev_hi_lim       bc_util        il_util            earliest_cr_line
count     1.236100e+06      1.236108e+06  1.242251e+06  432695.000000                     1306349
mean      1.741236e+05      3.268378e+04  6.005945e+01      71.520665  1999-02-15 15:15:33.603194
min       0.000000e+00      0.000000e+00  0.000000e+00       0.000000         1950-01-01 00:00:00
25%       4.960400e+04      1.400000e+04  3.850000e+01      59.000000         1995-04-01 00:00:00
50%       1.123900e+05      2.400000e+04  6.340000e+01      75.000000         2000-07-01 00:00:00
75%       2.518692e+05      4.050000e+04  8.490000e+01      87.000000         2004-06-01 00:00:00
max       8.700253e+06      2.013133e+06  1.086000e+02     150.000000         2015-09-01 00:00:00
std       1.752197e+05      3.319138e+04  2.823131e+01      22.719604                         NaN

In [62]:
# Cell 19 — actual missing % within your TRAINING window only (2007-2016), not the whole dataset
cluster_61 = ["il_util", "mths_since_rcnt_il", "all_util", "open_acc_6m", "total_cu_tl",
              "inq_last_12m", "open_il_12m", "max_bal_bc", "open_il_24m", "total_bal_il",
              "open_act_il", "inq_fi", "open_rv_12m", "open_rv_24m"]

train_mask = loan_df2["issue_year"] <= 2016
train_missing_pct = loan_df2.loc[train_mask, cluster_61].isna().mean() * 100
train_missing_pct.sort_values(ascending=False)

il_util               76.739775
mths_since_rcnt_il    73.998124
all_util              73.328934
open_acc_6m           73.327480
total_cu_tl           73.327480
inq_last_12m          73.327480
open_il_12m           73.327389
max_bal_bc            73.327389
open_il_24m           73.327389
total_bal_il          73.327389
open_act_il           73.327389
inq_fi                73.327389
open_rv_12m           73.327389
open_rv_24m           73.327389
dtype: float64

In [63]:
# Cell 20 — drop the structurally-unavailable cluster from your candidate list
cluster_61 = ["il_util", "mths_since_rcnt_il", "all_util", "open_acc_6m", "total_cu_tl",
              "inq_last_12m", "open_il_12m", "max_bal_bc", "open_il_24m", "total_bal_il",
              "open_act_il", "inq_fi", "open_rv_12m", "open_rv_24m"]

selected_47 = iv_results["name"].tolist()
final_candidates = [c for c in selected_47 if c not in cluster_61]

print(f"Dropped {len(cluster_61)} columns, {len(final_candidates)} remain")
final_candidates

Dropped 14 columns, 33 remain

['sub_grade',
 'int_rate',
 'grade',
 'term',
 'acc_open_past_24mths',
 'dti',
 'num_tl_op_past_12m',
 'bc_open_to_buy',
 'avg_cur_bal',
 'verification_status',
 'tot_hi_cred_lim',
 'total_bc_limit',
 'tot_cur_bal',
 'mo_sin_rcnt_tl',
 'mort_acc',
 'mths_since_recent_inq',
 'mo_sin_rcnt_rev_tl_op',
 'num_actv_rev_tl',
 'num_rev_tl_bal_gt_0',
 'funded_amnt',
 'loan_amnt',
 'total_rev_hi_lim',
 'funded_amnt_inv',
 'mths_since_recent_bc',
 'annual_inc',
 'percent_bc_gt_75',
 'installment',
 'mo_sin_old_rev_tl_op',
 'bc_util',
 'home_ownership',
 'inq_last_6mths',
 'earliest_cr_line',
 'revol_util']

In [64]:
# Cell 21 — check the 5.38% cluster within the training window
cluster_5 = ["avg_cur_bal", "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op",
             "num_tl_op_past_12m", "tot_cur_bal", "tot_hi_cred_lim",
             "num_rev_tl_bal_gt_0", "total_rev_hi_lim", "num_actv_rev_tl"]

loan_df2.loc[train_mask, cluster_5].isna().mean() * 100

avg_cur_bal              6.388157
mo_sin_old_rev_tl_op     6.387158
mo_sin_rcnt_rev_tl_op    6.387158
num_tl_op_past_12m       6.387067
tot_cur_bal              6.387067
tot_hi_cred_lim          6.387975
num_rev_tl_bal_gt_0      6.387067
total_rev_hi_lim         6.387339
num_actv_rev_tl          6.387067
dtype: float64

In [65]:
# Cell 22 — final candidate list after all cleaning and structural-missingness decisions
final_candidates = [c for c in selected_47 if c not in cluster_61]
print(f"{len(final_candidates)} columns remain")
final_candidates

33 columns remain

['sub_grade',
 'int_rate',
 'grade',
 'term',
 'acc_open_past_24mths',
 'dti',
 'num_tl_op_past_12m',
 'bc_open_to_buy',
 'avg_cur_bal',
 'verification_status',
 'tot_hi_cred_lim',
 'total_bc_limit',
 'tot_cur_bal',
 'mo_sin_rcnt_tl',
 'mort_acc',
 'mths_since_recent_inq',
 'mo_sin_rcnt_rev_tl_op',
 'num_actv_rev_tl',
 'num_rev_tl_bal_gt_0',
 'funded_amnt',
 'loan_amnt',
 'total_rev_hi_lim',
 'funded_amnt_inv',
 'mths_since_recent_bc',
 'annual_inc',
 'percent_bc_gt_75',
 'installment',
 'mo_sin_old_rev_tl_op',
 'bc_util',
 'home_ownership',
 'inq_last_6mths',
 'earliest_cr_line',
 'revol_util']

In [66]:
# Cell 24 — rebuild the training split from the CLEANED df
# (train_mask was already defined earlier as df["issue_year"] <= 2016)
X_train_clean = loan_df2.loc[train_mask, final_candidates]
y_train_clean = loan_df2.loc[train_mask, "target"].values

print(X_train_clean.shape)

(1100286, 33)

In [67]:
# Cell 25b — diagnose actual dtypes in your final candidate set
X_train_clean.dtypes.value_counts()

float64           25
str                5
int64              2
datetime64[us]     1
Name: count, dtype: int64

In [68]:
# Cell 25c — check the dtype of the specific columns you expect to be categorical
expected_categorical = ["sub_grade", "grade", "term", "verification_status", "home_ownership"]

for col in expected_categorical:
    if col in X_train_clean.columns:
        print(f"{col}: {X_train_clean[col].dtype}")
    else:
        print(f"{col}: NOT in final_candidates")

sub_grade: str
grade: str
term: str
verification_status: str
home_ownership: str

In [69]:
# Cell 25d — catch both object and category dtypes
categorical_final = X_train_clean.select_dtypes(include=["object", "category"]).columns.tolist()
numeric_final = X_train_clean.select_dtypes(include="number").columns.tolist()

print(f"Numeric: {len(numeric_final)}")
print(f"Categorical: {len(categorical_final)}")
categorical_final

Numeric: 27
Categorical: 5

C:\Users\hexs2\AppData\Local\Temp\ipykernel_26264\4257506124.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_final = X_train_clean.select_dtypes(include=["object", "category"]).columns.tolist()

['sub_grade', 'grade', 'term', 'verification_status', 'home_ownership']

In [71]:
# Cell 25e — engineer credit history length (months) from earliest_cr_line
loan_df2["credit_hist_months"] = (
    (loan_df2["issue_d"].dt.year - loan_df2["earliest_cr_line"].dt.year) * 12
    + (loan_df2["issue_d"].dt.month - loan_df2["earliest_cr_line"].dt.month)
)

loan_df2["credit_hist_months"].describe()

count    1.306349e+06
mean     1.949181e+02
std      8.993393e+01
min      6.000000e+00
25%      1.340000e+02
50%      1.770000e+02
75%      2.400000e+02
max      8.220000e+02
Name: credit_hist_months, dtype: float64

In [72]:
# Cell 25f — swap earliest_cr_line out for the derived numeric column in your candidate list
final_candidates = [c for c in final_candidates if c != "earliest_cr_line"]
final_candidates.append("credit_hist_months")

len(final_candidates)

33

In [73]:
# Cell 25g — rebuild X_train_clean now that the candidate list changed
X_train_clean = loan_df2.loc[train_mask, final_candidates]
y_train_clean = loan_df2.loc[train_mask, "target"].values

numeric_final = X_train_clean.select_dtypes(include=["number"]).columns.tolist()
categorical_final = X_train_clean.select_dtypes(include=["object", "category"]).columns.tolist()

print(f"Numeric: {len(numeric_final)}")
print(f"Categorical: {len(categorical_final)}")

Numeric: 28
Categorical: 5

C:\Users\hexs2\AppData\Local\Temp\ipykernel_26264\3017548046.py:6: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_final = X_train_clean.select_dtypes(include=["object", "category"]).columns.tolist()

In [74]:
# Cell 26 — rerun BinningProcess on the cleaned, final candidate set
binning_process_v2 = BinningProcess(
    variable_names=final_candidates,
    categorical_variables=categorical_final,
)

binning_process_v2.fit(X_train_clean, y_train_clean)

BinningProcess(categorical_variables=['sub_grade', 'grade', 'term',
                                      'verification_status', 'home_ownership'],
               variable_names=['sub_grade', 'int_rate', 'grade', 'term',
                               'acc_open_past_24mths', 'dti',
                               'num_tl_op_past_12m', 'bc_open_to_buy',
                               'avg_cur_bal', 'verification_status',
                               'tot_hi_cred_lim', 'total_bc_limit',
                               'tot_cur_bal', 'mo_sin_rcnt_tl', 'mort_acc',
                               'mths_since_recent_inq', 'mo_sin_rcnt_rev_tl_op',
                               'num_actv_rev_tl', 'num_rev_tl_bal_gt_0',
                               'funded_amnt', 'loan_amnt', 'total_rev_hi_lim',
                               'funded_amnt_inv', 'mths_since_recent_bc',
                               'annual_inc', 'percent_bc_gt_75', 'installment',
                               'mo_sin_old_rev_tl_op', 'bc_util',
                               'home_ownership', ...])

In [75]:
# Cell 27 — new IV/WOE summary, sorted strongest to weakest
summary_v2 = binning_process_v2.summary().sort_values("iv", ascending=False)
summary_v2[["name", "dtype", "n_bins", "iv", "gini", "quality_score"]]

                     name        dtype n_bins        iv      gini quality_score
0               sub_grade  categorical     15  0.493045  0.379064       0.93285
1                int_rate    numerical     13  0.466804  0.367367       0.94452
2                   grade  categorical      5  0.461965  0.361831      0.877571
3                    term  categorical      2  0.194665  0.199209      0.349357
4    acc_open_past_24mths    numerical      9  0.082744  0.162726      0.330147
5                     dti    numerical     16  0.078904  0.158976      0.228442
6      num_tl_op_past_12m    numerical      6  0.061737  0.139746      0.241433
7          bc_open_to_buy    numerical     13  0.057234  0.127446      0.181093
8             avg_cur_bal    numerical     14  0.053835  0.123163      0.125123
9     verification_status  categorical      3  0.052558  0.115064      0.179725
10        tot_hi_cred_lim    numerical     11  0.046923  0.114526      0.105413
11         total_bc_limit    numerical     14  0.043876  0.112452      0.095966
12            tot_cur_bal    numerical     13  0.042532   0.11468       0.16852
13         mo_sin_rcnt_tl    numerical     12   0.04186  0.114363      0.153301
14               mort_acc    numerical      6  0.039187  0.109116      0.144657
15  mths_since_recent_inq    numerical     12  0.038477   0.11053      0.033487
16  mo_sin_rcnt_rev_tl_op    numerical     13  0.033827  0.100942      0.029908
17        num_actv_rev_tl    numerical      9  0.033761  0.103231       0.13744
18    num_rev_tl_bal_gt_0    numerical      9  0.033323  0.102258      0.135206
19            funded_amnt    numerical      8  0.032291  0.099446      0.122629
20              loan_amnt    numerical      8  0.032266  0.099411      0.122982
21       total_rev_hi_lim    numerical     11  0.031809  0.091668      0.065319
22        funded_amnt_inv    numerical      8  0.031605  0.098488      0.120574
23   mths_since_recent_bc    numerical     11  0.031176  0.097742       0.11036
24             annual_inc    numerical     13  0.031043  0.098533      0.111413
25       percent_bc_gt_75    numerical      6  0.029118  0.095671      0.113666
26            installment    numerical      7  0.028205    0.0867      0.108158
27   mo_sin_old_rev_tl_op    numerical     11  0.028132  0.092282      0.075536
28                bc_util    numerical     13  0.026829  0.092752      0.079248
29         home_ownership  categorical      3  0.026816   0.08529      0.081346
30         inq_last_6mths    numerical      4  0.026774  0.084089      0.079116
31             revol_util    numerical     13  0.020792   0.07718      0.040053
32     credit_hist_months    numerical     12  0.010083  0.057144      0.003547

In [76]:
# Cell 28 — compare against the original (pre-cleaning) result to see what shifted
comparison = summary.set_index("name")[["iv"]].rename(columns={"iv": "iv_before"}).join(
    summary_v2.set_index("name")[["iv"]].rename(columns={"iv": "iv_after"}),
    how="inner"
)
comparison["iv_change"] = comparison["iv_after"] - comparison["iv_before"]
comparison.sort_values("iv_change", ascending=False)

                      iv_before  iv_after iv_change
name
tot_hi_cred_lim        0.046921  0.046923  0.000002
sub_grade              0.493045  0.493045       0.0
int_rate               0.466804  0.466804       0.0
inq_last_6mths         0.026774  0.026774       0.0
home_ownership         0.026816  0.026816       0.0
bc_util                0.026829  0.026829       0.0
mo_sin_old_rev_tl_op   0.028132  0.028132       0.0
installment            0.028205  0.028205       0.0
percent_bc_gt_75       0.029118  0.029118       0.0
annual_inc             0.031043  0.031043       0.0
mths_since_recent_bc   0.031176  0.031176       0.0
funded_amnt_inv        0.031605  0.031605       0.0
loan_amnt              0.032266  0.032266       0.0
funded_amnt            0.032291  0.032291       0.0
num_rev_tl_bal_gt_0    0.033323  0.033323       0.0
num_actv_rev_tl        0.033761  0.033761       0.0
mo_sin_rcnt_rev_tl_op  0.033827  0.033827       0.0
mths_since_recent_inq  0.038477  0.038477       0.0
mort_acc               0.039187  0.039187       0.0
mo_sin_rcnt_tl          0.04186   0.04186       0.0
tot_cur_bal            0.042532  0.042532       0.0
total_bc_limit         0.043876  0.043876       0.0
verification_status    0.052558  0.052558       0.0
avg_cur_bal            0.053835  0.053835       0.0
bc_open_to_buy         0.057234  0.057234       0.0
num_tl_op_past_12m     0.061737  0.061737       0.0
dti                    0.078904  0.078904       0.0
acc_open_past_24mths   0.082744  0.082744       0.0
term                   0.194665  0.194665       0.0
grade                  0.461965  0.461965       0.0
revol_util             0.020792  0.020792       0.0
total_rev_hi_lim        0.03181  0.031809 -0.000001